[package]
name = "typmark-cli"
version = "0.3.0-beta.2"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
typmark-core = { path = "../typmark-core" }
typmark-renderer = { path = "../typmark-renderer" }
