[package]
name = "typmark-renderer"
version = "0.3.0-beta.1"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
syntect = "5.3.0"
