[package]
name = "typmark-renderer"
version = "0.2.0-beta.6"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
syntect = "5.3.0"
